// This file is automatically generated during the build process
declare namespace App {
    interface Locals { }
    interface PageData { }
    interface Platform { }
    interface Session { }
    interface Stuff { }
}

declare module '@sveltejs/kit' {
    interface PageParams {
        slug: string;
    }

    // If you need additional types, you can add them here.
}

export type PageLoad = {
    // define the structure of PageLoad here
};